'use strict';

var items_all = [
    {id: 'abyssal_lagiacrus', name: 'Abyssal Lagiacrus',
        image: 'image/official_thumbnail/Abyssal_Lagiacrus.png'},
    {id: 'acidic_glavenus', name: 'Acidic Glavenus',
        image: 'image/official_thumbnail/Acidic_Glavenus.png'},
    {id: 'agnaktor', name: 'Agnaktor',
        image: 'image/official_thumbnail/Agnaktor.png'},
    {id: 'ahtal-ka', name: 'Ahtal-Ka',
        image: 'image/official_thumbnail/Ahtal-Ka.png'},
    {id: 'ahtal-neset', name: 'Ahtal-Neset',
        image: 'image/official_thumbnail/Ahtal-Neset.png'},
    {id: 'akantor', name: 'Akantor',
        image: 'image/official_thumbnail/Akantor.png'},
    {id: 'aknosom', name: 'Aknosom',
        image: 'image/official_thumbnail/Aknosom.png'},
    {id: 'alatreon', name: 'Alatreon',
        image: 'image/official_thumbnail/Alatreon.png'},
    {id: 'almudron', name: 'Almudron',
        image: 'image/official_thumbnail/Almudron.png'},
    {id: 'amatsu', name: 'Amatsu',
        image: 'image/official_thumbnail/Amatsu.png'},
    {id: 'anjanath', name: 'Anjanath',
        image: 'image/official_thumbnail/Anjanath.png'},
    {id: 'apex_arzuros', name: 'Apex Arzuros',
        image: 'image/official_thumbnail/Apex_Arzuros.png'},
    {id: 'apex_diablos', name: 'Apex Diablos',
        image: 'image/official_thumbnail/Apex_Diablos.png'},
    {id: 'apex_mizutsune', name: 'Apex Mizutsune',
        image: 'image/official_thumbnail/Apex_Mizutsune.png'},
    {id: 'apex_rathalos', name: 'Apex Rathalos',
        image: 'image/official_thumbnail/Apex_Rathalos.png'},
    {id: 'apex_rathian', name: 'Apex Rathian',
        image: 'image/official_thumbnail/Apex_Rathian.png'},
    {id: 'apex_zinogre', name: 'Apex Zinogre',
        image: 'image/official_thumbnail/Apex_Zinogre.png'},
    {id: 'arzuros', name: 'Arzuros',
        image: 'image/official_thumbnail/Arzuros.png'},
    {id: 'ashen_lao-shan_lung', name: 'Ashen Lao-Shan Lung',
        image: 'image/official_thumbnail/Ashen_Lao-Shan_Lung.png'},
    {id: 'ash_kecha_wacha', name: 'Ash Kecha Wacha',
        image: 'image/official_thumbnail/Ash_Kecha_Wacha.png'},
    {id: 'astalos', name: 'Astalos',
        image: 'image/official_thumbnail/Astalos.png'},
    {id: 'aurora_somnacanth', name: 'Aurora Somnacanth',
        image: 'image/official_thumbnail/Aurora_Somnacanth.png'},
    {id: 'azure_rathalos', name: 'Azure Rathalos',
        image: 'image/official_thumbnail/Azure_Rathalos.png'},
    {id: 'baleful_gigginox', name: 'Baleful Gigginox',
        image: 'image/official_thumbnail/Baleful_Gigginox.png'},
    {id: 'banbaro', name: 'Banbaro',
        image: 'image/official_thumbnail/Banbaro.png'},
    {id: 'barioth', name: 'Barioth',
        image: 'image/official_thumbnail/Barioth.png'},
    {id: 'barroth', name: 'Barroth',
        image: 'image/official_thumbnail/Barroth.png'},
    {id: 'basarios', name: 'Basarios',
        image: 'image/official_thumbnail/Basarios.png'},
    {id: 'bazelgeuse', name: 'Bazelgeuse',
        image: 'image/official_thumbnail/Bazelgeuse.png'},
    {id: 'beotodus', name: 'Beotodus',
        image: 'image/official_thumbnail/Beotodus.png'},
    {id: 'berserk_tetsucabra', name: 'Berserk Tetsucabra',
        image: 'image/official_thumbnail/Berserk_Tetsucabra.png'},
    {id: 'bishaten', name: 'Bishaten',
        image: 'image/official_thumbnail/Bishaten.png'},
    {id: 'blackveil_vaal_hazak', name: 'Blackveil Vaal Hazak',
        image: 'image/official_thumbnail/Blackveil_Vaal_Hazak.png'},
    {id: 'black_diablos', name: 'Black Diablos',
        image: 'image/official_thumbnail/Black_Diablos.png'},
    {id: 'black_gravios', name: 'Black Gravios',
        image: 'image/official_thumbnail/Black_Gravios.png'},
    {id: 'blangonga', name: 'Blangonga',
        image: 'image/official_thumbnail/Blangonga.png'},
    {id: 'bloodbath_diablos', name: 'Bloodbath Diablos',
        image: 'image/official_thumbnail/Bloodbath_Diablos.png'},
    {id: 'blood_orange_bishaten', name: 'Blood Orange Bishaten',
        image: 'image/official_thumbnail/Blood_Orange_Bishaten.png'},
    {id: 'blue_yian_kut-ku', name: 'Blue Yian Kut-Ku',
        image: 'image/official_thumbnail/Blue_Yian_Kut-Ku.png'},
    {id: 'boltreaver_astalos', name: 'Boltreaver Astalos',
        image: 'image/official_thumbnail/Boltreaver_Astalos.png'},
    {id: 'brachydios', name: 'Brachydios',
        image: 'image/official_thumbnail/Brachydios.png'},
    {id: 'brute_tigrex', name: 'Brute Tigrex',
        image: 'image/official_thumbnail/Brute_Tigrex.png'},
    {id: 'bulldrome', name: 'Bulldrome',
        image: 'image/official_thumbnail/Bulldrome.png'},
    {id: 'ceadeus', name: 'Ceadeus',
        image: 'image/official_thumbnail/Ceadeus.png'},
    {id: 'cephadrome', name: 'Cephadrome',
        image: 'image/official_thumbnail/Cephadrome.png'},
    {id: 'chameleos', name: 'Chameleos',
        image: 'image/official_thumbnail/Chameleos.png'},
    {id: 'chaotic_gore_magala', name: 'Chaotic Gore Magala',
        image: 'image/official_thumbnail/Chaotic_Gore_Magala.png'},
    {id: 'congalala', name: 'Congalala',
        image: 'image/official_thumbnail/Congalala.png'},
    {id: 'copper_blangonga', name: 'Copper Blangonga',
        image: 'image/official_thumbnail/Copper_Blangonga.png'},
    {id: 'coral_pukei-pukei', name: 'Coral Pukei-Pukei',
        image: 'image/official_thumbnail/Coral_Pukei-Pukei.png'},
    {id: 'crimson_fatalis', name: 'Crimson Fatalis',
        image: 'image/official_thumbnail/Crimson_Fatalis.png'},
    {id: 'crimson_glow_valstrax', name: 'Crimson Glow Valstrax',
        image: 'image/official_thumbnail/Crimson_Glow_Valstrax.png'},
    {id: 'crimson_qurupeco', name: 'Crimson Qurupeco',
        image: 'image/official_thumbnail/Crimson_Qurupeco.png'},
    {id: 'crystalbeard_uragaan', name: 'Crystalbeard Uragaan',
        image: 'image/official_thumbnail/Crystalbeard_Uragaan.png'},
    {id: 'dah-ren_mohran', name: 'Dah\'ren Mohran',
        image: 'image/official_thumbnail/Dah\'ren_Mohran.png'},
    {id: 'daimyo_hermitaur', name: 'Daimyo Hermitaur',
        image: 'image/official_thumbnail/Daimyo_Hermitaur.png'},
    {id: 'dalamadur', name: 'Dalamadur',
        image: 'image/official_thumbnail/Dalamadur.png'},
    {id: 'deadeye_yian_garuga', name: 'Deadeye Yian Garuga',
        image: 'image/official_thumbnail/Deadeye_Yian_Garuga.png'},
    {id: 'desert_seltas', name: 'Desert Seltas',
        image: 'image/official_thumbnail/Desert_Seltas.png'},
    {id: 'desert_seltas_queen', name: 'Desert Seltas Queen',
        image: 'image/official_thumbnail/Desert_Seltas_Queen.png'},
    {id: 'deviljho', name: 'Deviljho',
        image: 'image/official_thumbnail/Deviljho.png'},
    {id: 'diablos', name: 'Diablos',
        image: 'image/official_thumbnail/Diablos.png'},
    {id: 'dire_miralis', name: 'Dire Miralis',
        image: 'image/official_thumbnail/Dire_Miralis.png'},
    {id: 'dodogama', name: 'Dodogama',
        image: 'image/official_thumbnail/Dodogama.png'},
    {id: 'dreadking_rathalos', name: 'Dreadking Rathalos',
        image: 'image/official_thumbnail/Dreadking_Rathalos.png'},
    {id: 'dreadqueen_rathian', name: 'Dreadqueen Rathian',
        image: 'image/official_thumbnail/Dreadqueen_Rathian.png'},
    {id: 'drilltusk_tetsucabra', name: 'Drilltusk Tetsucabra',
        image: 'image/official_thumbnail/Drilltusk_Tetsucabra.png'},
    {id: 'duramboros', name: 'Duramboros',
        image: 'image/official_thumbnail/Duramboros.png'},
    {id: 'ebony_odogaron', name: 'Ebony Odogaron',
        image: 'image/official_thumbnail/Ebony_Odogaron.png'},
    {id: 'elderfrost_gammoth', name: 'Elderfrost Gammoth',
        image: 'image/official_thumbnail/Elderfrost_Gammoth.png'},
    {id: 'emerald_congalala', name: 'Emerald Congalala',
        image: 'image/official_thumbnail/Emerald_Congalala.png'},
    {id: 'espinas', name: 'Espinas',
        image: 'image/official_thumbnail/Espinas.png'},
    {id: 'fatalis', name: 'Fatalis',
        image: 'image/official_thumbnail/Fatalis.png'},
    {id: 'flaming_espinas', name: 'Flaming Espinas',
        image: 'image/official_thumbnail/Flaming_Espinas.png'},
    {id: 'frostfang_barioth', name: 'Frostfang Barioth',
        image: 'image/official_thumbnail/Frostfang_Barioth.png'},
    {id: 'fulgur_anjanath', name: 'Fulgur Anjanath',
        image: 'image/official_thumbnail/Fulgur_Anjanath.png'},
    {id: 'furious_rajang', name: 'Furious Rajang',
        image: 'image/official_thumbnail/Furious_Rajang.png'},
    {id: 'gaismagorm', name: 'Gaismagorm',
        image: 'image/official_thumbnail/Gaismagorm.png'},
    {id: 'gammoth', name: 'Gammoth',
        image: 'image/official_thumbnail/Gammoth.png'},
    {id: 'garangolm', name: 'Garangolm',
        image: 'image/official_thumbnail/Garangolm.png'},
    {id: 'gendrome', name: 'Gendrome',
        image: 'image/official_thumbnail/Gendrome.png'},
    {id: 'giadrome', name: 'Giadrome',
        image: 'image/official_thumbnail/Giadrome.png'},
    {id: 'gigginox', name: 'Gigginox',
        image: 'image/official_thumbnail/Gigginox.png'},
    {id: 'glacial_agnaktor', name: 'Glacial Agnaktor',
        image: 'image/official_thumbnail/Glacial_Agnaktor.png'},
    {id: 'glavenus', name: 'Glavenus',
        image: 'image/official_thumbnail/Glavenus.png'},
    {id: 'gobul', name: 'Gobul',
        image: 'image/official_thumbnail/Gobul.png'},
    {id: 'gogmazios', name: 'Gogmazios',
        image: 'image/official_thumbnail/Gogmazios.png'},
    {id: 'goldbeard_ceadeus', name: 'Goldbeard Ceadeus',
        image: 'image/official_thumbnail/Goldbeard_Ceadeus.png'},
    {id: 'gold_rathian', name: 'Gold Rathian',
        image: 'image/official_thumbnail/Gold_Rathian.png'},
    {id: 'gore_magala', name: 'Gore Magala',
        image: 'image/official_thumbnail/Gore_Magala.png'},
    {id: 'goss_harag', name: 'Goss Harag',
        image: 'image/official_thumbnail/Goss_Harag.png'},
    {id: 'gravios', name: 'Gravios',
        image: 'image/official_thumbnail/Gravios.png'},
    {id: 'great_baggi', name: 'Great Baggi',
        image: 'image/official_thumbnail/Great_Baggi.png'},
    {id: 'great_girros', name: 'Great Girros',
        image: 'image/official_thumbnail/Great_Girros.png'},
    {id: 'great_izuchi', name: 'Great Izuchi',
        image: 'image/official_thumbnail/Great_Izuchi.png'},
    {id: 'great_jaggi', name: 'Great Jaggi',
        image: 'image/official_thumbnail/Great_Jaggi.png'},
    {id: 'great_jagras', name: 'Great Jagras',
        image: 'image/official_thumbnail/Great_Jagras.png'},
    {id: 'great_maccao', name: 'Great Maccao',
        image: 'image/official_thumbnail/Great_Maccao.png'},
    {id: 'great_wroggi', name: 'Great Wroggi',
        image: 'image/official_thumbnail/Great_Wroggi.png'},
    {id: 'green_nargacuga', name: 'Green Nargacuga',
        image: 'image/official_thumbnail/Green_Nargacuga.png'},
    {id: 'green_plesioth', name: 'Green Plesioth',
        image: 'image/official_thumbnail/Green_Plesioth.png'},
    {id: 'grimclaw_tigrex', name: 'Grimclaw Tigrex',
        image: 'image/official_thumbnail/Grimclaw_Tigrex.png'},
    {id: 'gypceros', name: 'Gypceros',
        image: 'image/official_thumbnail/Gypceros.png'},
    {id: 'hallowed_jhen_mohran', name: 'Hallowed Jhen Mohran',
        image: 'image/official_thumbnail/Hallowed_Jhen_Mohran.png'},
    {id: 'hellblade_glavenus', name: 'Hellblade Glavenus',
        image: 'image/official_thumbnail/Hellblade_Glavenus.png'},
    {id: 'hypnocatrice', name: 'Hypnocatrice',
        image: 'image/official_thumbnail/Hypnocatrice.png'},
    {id: 'iodrome', name: 'Iodrome',
        image: 'image/official_thumbnail/Iodrome.png'},
    {id: 'ivory_lagiacrus', name: 'Ivory Lagiacrus',
        image: 'image/official_thumbnail/Ivory_Lagiacrus.png'},
    {id: 'jade_barroth', name: 'Jade Barroth',
        image: 'image/official_thumbnail/Jade_Barroth.png'},
    {id: 'jhen_mohran', name: 'Jhen Mohran',
        image: 'image/official_thumbnail/Jhen_Mohran.png'},
    {id: 'jyuratodus', name: 'Jyuratodus',
        image: 'image/official_thumbnail/Jyuratodus.png'},
    {id: 'kecha_wacha', name: 'Kecha Wacha',
        image: 'image/official_thumbnail/Kecha_Wacha.png'},
    {id: 'khezu', name: 'Khezu',
        image: 'image/official_thumbnail/Khezu.png'},
    {id: 'king_shakalaka', name: 'King Shakalaka',
        image: 'image/official_thumbnail/King_Shakalaka.png'},
    {id: 'kirin', name: 'Kirin',
        image: 'image/official_thumbnail/Kirin.png'},
    {id: 'kulu-ya-ku', name: 'Kulu-Ya-Ku',
        image: 'image/official_thumbnail/Kulu-Ya-Ku.png'},
    {id: 'kulve_taroth', name: 'Kulve Taroth',
        image: 'image/official_thumbnail/Kulve_Taroth.png'},
    {id: 'kushala_daora', name: 'Kushala Daora',
        image: 'image/official_thumbnail/Kushala_Daora.png'},
    {id: 'lagiacrus', name: 'Lagiacrus',
        image: 'image/official_thumbnail/Lagiacrus.png'},
    {id: 'lagombi', name: 'Lagombi',
        image: 'image/official_thumbnail/Lagombi.png'},
    {id: 'lao-shan_lung', name: 'Lao-Shan Lung',
        image: 'image/official_thumbnail/Lao-Shan_Lung.png'},
    {id: 'lavasioth', name: 'Lavasioth',
        image: 'image/official_thumbnail/Lavasioth.png'},
    {id: 'legiana', name: 'Legiana',
        image: 'image/official_thumbnail/Legiana.png'},
    {id: 'lucent_nargacuga', name: 'Lucent Nargacuga',
        image: 'image/official_thumbnail/Lucent_Nargacuga.png'},
    {id: 'lunagaron', name: 'Lunagaron',
        image: 'image/official_thumbnail/Lunagaron.png'},
    {id: 'lunastra', name: 'Lunastra',
        image: 'image/official_thumbnail/Lunastra.png'},
    {id: 'magma_almudron', name: 'Magma Almudron',
        image: 'image/official_thumbnail/Magma_Almudron.png'},
    {id: 'magnamalo', name: 'Magnamalo',
        image: 'image/official_thumbnail/Magnamalo.png'},
    {id: 'malfestio', name: 'Malfestio',
        image: 'image/official_thumbnail/Malfestio.png'},
    {id: 'malzeno', name: 'Malzeno',
        image: 'image/official_thumbnail/Malzeno.png'},
    {id: 'mizutsune', name: 'Mizutsune',
        image: 'image/official_thumbnail/Mizutsune.png'},
    {id: 'molten_tigrex', name: 'Molten Tigrex',
        image: 'image/official_thumbnail/Molten_Tigrex.png'},
    {id: 'monoblos', name: 'Monoblos',
        image: 'image/official_thumbnail/Monoblos.png'},
    {id: 'najarala', name: 'Najarala',
        image: 'image/official_thumbnail/Najarala.png'},
    {id: 'nakarkos', name: 'Nakarkos',
        image: 'image/official_thumbnail/Nakarkos.png'},
    {id: 'namielle', name: 'Namielle',
        image: 'image/official_thumbnail/Namielle.png'},
    {id: 'nargacuga', name: 'Nargacuga',
        image: 'image/official_thumbnail/Nargacuga.png'},
    {id: 'narwa_the_allmother', name: 'Narwa the Allmother',
        image: 'image/official_thumbnail/Narwa_the_Allmother.png'},
    {id: 'nergigante', name: 'Nergigante',
        image: 'image/official_thumbnail/Nergigante.png'},
    {id: 'nerscylla', name: 'Nerscylla',
        image: 'image/official_thumbnail/Nerscylla.png'},
    {id: 'nibelsnarf', name: 'Nibelsnarf',
        image: 'image/official_thumbnail/Nibelsnarf.png'},
    {id: 'nightcloak_malfestio', name: 'Nightcloak Malfestio',
        image: 'image/official_thumbnail/Nightcloak_Malfestio.png'},
    {id: 'nightshade_paolumu', name: 'Nightshade Paolumu',
        image: 'image/official_thumbnail/Nightshade_Paolumu.png'},
    {id: 'odogaron', name: 'Odogaron',
        image: 'image/official_thumbnail/Odogaron.png'},
    {id: 'old_fatalis', name: 'Old Fatalis',
        image: 'image/official_thumbnail/Old_Fatalis.png'},
    {id: 'oroshi_kirin', name: 'Oroshi Kirin',
        image: 'image/official_thumbnail/Oroshi_Kirin.png'},
    {id: 'paolumu', name: 'Paolumu',
        image: 'image/official_thumbnail/Paolumu.png'},
    {id: 'pink_rathian', name: 'Pink Rathian',
        image: 'image/official_thumbnail/Pink_Rathian.png'},
    {id: 'plesioth', name: 'Plesioth',
        image: 'image/official_thumbnail/Plesioth.png'},
    {id: 'plum_daimyo_hermitaur', name: 'Plum Daimyo Hermitaur',
        image: 'image/official_thumbnail/Plum_Daimyo_Hermitaur.png'},
    {id: 'primordial_malzeno', name: 'Primordial Malzeno',
        image: 'image/official_thumbnail/Primordial_Malzeno.png'},
    {id: 'pukei-pukei', name: 'Pukei-Pukei',
        image: 'image/official_thumbnail/Pukei-Pukei.png'},
    {id: 'purple_gypceros', name: 'Purple Gypceros',
        image: 'image/official_thumbnail/Purple_Gypceros.png'},
    {id: 'purple_ludroth', name: 'Purple Ludroth',
        image: 'image/official_thumbnail/Purple_Ludroth.png'},
    {id: 'pyre_rakna-kadaki', name: 'Pyre Rakna-Kadaki',
        image: 'image/official_thumbnail/Pyre_Rakna-Kadaki.png'},
    {id: 'qurupeco', name: 'Qurupeco',
        image: 'image/official_thumbnail/Qurupeco.png'},
    {id: 'radobaan', name: 'Radobaan',
        image: 'image/official_thumbnail/Radobaan.png'},
    {id: 'raging_brachydios', name: 'Raging Brachydios',
        image: 'image/official_thumbnail/Raging_Brachydios.png'},
    {id: 'rajang', name: 'Rajang',
        image: 'image/official_thumbnail/Rajang.png'},
    {id: 'rakna-kadaki', name: 'Rakna-Kadaki',
        image: 'image/official_thumbnail/Rakna-Kadaki.png'},
    {id: 'rathalos', name: 'Rathalos',
        image: 'image/official_thumbnail/Rathalos.png'},
    {id: 'rathian', name: 'Rathian',
        image: 'image/official_thumbnail/Rathian.png'},
    {id: 'redhelm_arzuros', name: 'Redhelm Arzuros',
        image: 'image/official_thumbnail/Redhelm_Arzuros.png'},
    {id: 'red_khezu', name: 'Red Khezu',
        image: 'image/official_thumbnail/Red_Khezu.png'},
    {id: 'risen_chameleos', name: 'Risen Chameleos',
        image: 'image/official_thumbnail/Risen_Chameleos.png'},
    {id: 'risen_crimson_glow_valstrax', name: 'Risen Crimson Glow Valstrax',
        image: 'image/official_thumbnail/Risen_Crimson_Glow_Valstrax.png'},
    {id: 'risen_kushala_daora', name: 'Risen Kushala Daora',
        image: 'image/official_thumbnail/Risen_Kushala_Daora.png'},
    {id: 'risen_shagaru_magala', name: 'Risen Shagaru Magala',
        image: 'image/official_thumbnail/Risen_Shagaru_Magala.png'},
    {id: 'risen_teostra', name: 'Risen Teostra',
        image: 'image/official_thumbnail/Risen_Teostra.png'},
    {id: 'royal_ludroth', name: 'Royal Ludroth',
        image: 'image/official_thumbnail/Royal_Ludroth.png'},
    {id: 'ruby_basarios', name: 'Ruby Basarios',
        image: 'image/official_thumbnail/Ruby_Basarios.png'},
    {id: 'ruiner_nergigante', name: 'Ruiner Nergigante',
        image: 'image/official_thumbnail/Ruiner_Nergigante.png'},
    {id: 'rusted_kushala_daora', name: 'Rusted Kushala Daora',
        image: 'image/official_thumbnail/Rusted_Kushala_Daora.png'},
    {id: 'rustrazor_ceanataur', name: 'Rustrazor Ceanataur',
        image: 'image/official_thumbnail/Rustrazor_Ceanataur.png'},
    {id: 'rust_duramboros', name: 'Rust Duramboros',
        image: 'image/official_thumbnail/Rust_Duramboros.png'},
    {id: 'safi-jiiva', name: 'Safi\'jiiva',
        image: 'image/official_thumbnail/Safi\'jiiva.png'},
    {id: 'sand_barioth', name: 'Sand Barioth',
        image: 'image/official_thumbnail/Sand_Barioth.png'},
    {id: 'savage_deviljho', name: 'Savage Deviljho',
        image: 'image/official_thumbnail/Savage_Deviljho.png'},
    {id: 'scarred_yian_garuga', name: 'Scarred Yian Garuga',
        image: 'image/official_thumbnail/Scarred_Yian_Garuga.png'},
    {id: 'scorned_magnamalo', name: 'Scorned Magnamalo',
        image: 'image/official_thumbnail/Scorned_Magnamalo.png'},
    {id: 'seething_bazelgeuse', name: 'Seething Bazelgeuse',
        image: 'image/official_thumbnail/Seething_Bazelgeuse.png'},
    {id: 'seltas', name: 'Seltas',
        image: 'image/official_thumbnail/Seltas.png'},
    {id: 'seltas_queen', name: 'Seltas Queen',
        image: 'image/official_thumbnail/Seltas_Queen.png'},
    {id: 'seregios', name: 'Seregios',
        image: 'image/official_thumbnail/Seregios.png'},
    {id: 'shagaru_magala', name: 'Shagaru Magala',
        image: 'image/official_thumbnail/Shagaru_Magala.png'},
    {id: 'shah_dalamadur', name: 'Shah Dalamadur',
        image: 'image/official_thumbnail/Shah_Dalamadur.png'},
    {id: 'shara_ishvalda', name: 'Shara Ishvalda',
        image: 'image/official_thumbnail/Shara_Ishvalda.png'},
    {id: 'shen_gaoren', name: 'Shen Gaoren',
        image: 'image/official_thumbnail/Shen_Gaoren.png'},
    {id: 'shogun_ceanataur', name: 'Shogun Ceanataur',
        image: 'image/official_thumbnail/Shogun_Ceanataur.png'},
    {id: 'shrieking_legiana', name: 'Shrieking Legiana',
        image: 'image/official_thumbnail/Shrieking_Legiana.png'},
    {id: 'shrouded_nerscylla', name: 'Shrouded Nerscylla',
        image: 'image/official_thumbnail/Shrouded_Nerscylla.png'},
    {id: 'silverwind_nargacuga', name: 'Silverwind Nargacuga',
        image: 'image/official_thumbnail/Silverwind_Nargacuga.png'},
    {id: 'silver_rathalos', name: 'Silver Rathalos',
        image: 'image/official_thumbnail/Silver_Rathalos.png'},
    {id: 'snowbaron_lagombi', name: 'Snowbaron Lagombi',
        image: 'image/official_thumbnail/Snowbaron_Lagombi.png'},
    {id: 'somnacanth', name: 'Somnacanth',
        image: 'image/official_thumbnail/Somnacanth.png'},
    {id: 'soulseer_mizutsune', name: 'Soulseer Mizutsune',
        image: 'image/official_thumbnail/Soulseer_Mizutsune.png'},
    {id: 'steel_uragaan', name: 'Steel Uragaan',
        image: 'image/official_thumbnail/Steel_Uragaan.png'},
    {id: 'stonefist_hermitaur', name: 'Stonefist Hermitaur',
        image: 'image/official_thumbnail/Stonefist_Hermitaur.png'},
    {id: 'stygian_zinogre', name: 'Stygian Zinogre',
        image: 'image/official_thumbnail/Stygian_Zinogre.png'},
    {id: 'teostra', name: 'Teostra',
        image: 'image/official_thumbnail/Teostra.png'},
    {id: 'terra_shogun_ceanataur', name: 'Terra Shogun Ceanataur',
        image: 'image/official_thumbnail/Terra_Shogun_Ceanataur.png'},
    {id: 'tetranadon', name: 'Tetranadon',
        image: 'image/official_thumbnail/Tetranadon.png'},
    {id: 'tetsucabra', name: 'Tetsucabra',
        image: 'image/official_thumbnail/Tetsucabra.png'},
    {id: 'thunderlord_zinogre', name: 'Thunderlord Zinogre',
        image: 'image/official_thumbnail/Thunderlord_Zinogre.png'},
    {id: 'thunder_serpent_narwa', name: 'Thunder Serpent Narwa',
        image: 'image/official_thumbnail/Thunder_Serpent_Narwa.png'},
    {id: 'tidal_najarala', name: 'Tidal Najarala',
        image: 'image/official_thumbnail/Tidal_Najarala.png'},
    {id: 'tigerstripe_zamtrios', name: 'Tigerstripe Zamtrios',
        image: 'image/official_thumbnail/Tigerstripe_Zamtrios.png'},
    {id: 'tigrex', name: 'Tigrex',
        image: 'image/official_thumbnail/Tigrex.png'},
    {id: 'tobi-kadachi', name: 'Tobi-Kadachi',
        image: 'image/official_thumbnail/Tobi-Kadachi.png'},
    {id: 'tzitzi-ya-ku', name: 'Tzitzi-Ya-Ku',
        image: 'image/official_thumbnail/Tzitzi-Ya-Ku.png'},
    {id: 'ukanlos', name: 'Ukanlos',
        image: 'image/official_thumbnail/Ukanlos.png'},
    {id: 'uragaan', name: 'Uragaan',
        image: 'image/official_thumbnail/Uragaan.png'},
    {id: 'vaal_hazak', name: 'Vaal Hazak',
        image: 'image/official_thumbnail/Vaal_Hazak.png'},
    {id: 'valstrax', name: 'Valstrax',
        image: 'image/official_thumbnail/Valstrax.png'},
    {id: 'velkhana', name: 'Velkhana',
        image: 'image/official_thumbnail/Velkhana.png'},
    {id: 'velocidrome', name: 'Velocidrome',
        image: 'image/official_thumbnail/Velocidrome.png'},
    {id: 'vespoid_queen', name: 'Vespoid Queen',
        image: 'image/official_thumbnail/Vespoid_Queen.png'},
    {id: 'violet_mizutsune', name: 'Violet Mizutsune',
        image: 'image/official_thumbnail/Violet_Mizutsune.png'},
    {id: 'viper_tobi-kadachi', name: 'Viper Tobi-Kadachi',
        image: 'image/official_thumbnail/Viper_Tobi-Kadachi.png'},
    {id: 'volvidon', name: 'Volvidon',
        image: 'image/official_thumbnail/Volvidon.png'},
    {id: 'white_monoblos', name: 'White Monoblos',
        image: 'image/official_thumbnail/White_Monoblos.png'},
    {id: 'wind_serpent_ibushi', name: 'Wind Serpent Ibushi',
        image: 'image/official_thumbnail/Wind_Serpent_Ibushi.png'},
    {id: 'xeno-jiiva', name: 'Xeno\'jiiva',
        image: 'image/official_thumbnail/Xeno\'jiiva.png'},
    {id: 'yama_tsukami', name: 'Yama Tsukami',
        image: 'image/official_thumbnail/Yama_Tsukami.png'},
    {id: 'yian_garuga', name: 'Yian Garuga',
        image: 'image/official_thumbnail/Yian_Garuga.png'},
    {id: 'yian_kut-ku', name: 'Yian Kut-Ku',
        image: 'image/official_thumbnail/Yian_Kut-Ku.png'},
    {id: 'zamtrios', name: 'Zamtrios',
        image: 'image/official_thumbnail/Zamtrios.png'},
    {id: 'zinogre', name: 'Zinogre',
        image: 'image/official_thumbnail/Zinogre.png'},
    {id: 'zorah_magdaros', name: 'Zorah Magdaros',
        image: 'image/official_thumbnail/Zorah_Magdaros.png'},
];

var monsters_in_game = {
    world: [
        'anjanath', 'barroth', 'bazelgeuse', 'behemoth', 'deviljho', 'diablos', 'black_diablos',
        'dodogama', 'great_girros', 'great_jagras', 'jyuratodus',
        'kirin', 'kulu-ya-ku', 'kulve_taroth', 'kushala_daora', 'lavasioth', 'legiana', 'lunastra',
        'odogaron', 'nergigante', 'paolumu', 'pukei-pukei', 'radobaan',
        'rathalos', 'azure_rathalos', 'rathian', 'pink_rathian',
        'teostra', 'tobi-kadachi', 'tzitzi-ya-ku', 'uragaan', 'vaal_hazak',
        'xeno-jiiva', 'zorah_magdaros', 
    ],
    iceborne: [
        'alatreon', 'fulgur_anjanath', 'banbaro', 'barioth', 'frostfang_barioth',
        'seething_bazelgeuse', 'beotodus', 'brachydios', 'raging_brachydios', 'savage_deviljho',
        'fatalis', 'glavenus', 'acidic_glavenus', 'shrieking_legiana', 'ebony_odogaron', 'namielle',
        'nargacuga', 'ruiner_nergigante', 'nightshade_paolumu', 'coral_pukei-pukei',
        'rajang', 'furious_rajang', 'silver_rathalos', 'gold_rathian', 'safi-jiiva',
        'shara_ishvalda', 'tigrex', 'brute_tigrex', 'viper_tobi-kadachi', 'blackveil_vaal_hazak',
        'velkhana', 'yian_garuga', 'scarred_yian_garuga', 'zinogre', 'stygian_zinogre', 
    ],
    rise: [
        'aknosom', 'almudron', 'anjanath', 'arzuros', 'apex_arzuros',
        'barioth', 'barroth', 'bazelgeuse', 'basarios', 'bishaten', 'chameleos',
        'diablos', 'apex_diablos', 'goss_harag', 'great_baggi', 'great_izuchi', 'great_wroggi',
        'jyuratodus', 'khezu', 'kulu-ya-ku', 'kushala_daora', 'lagombi', 'magnamalo',
        'mizutsune', 'apex_mizutsune', 'nargacuga', 'pukei-pukei', 'rajang', 'rakna-kadaki',
        'rathalos', 'apex_rathalos', 'rathian', 'apex_rathian', 'royal_ludroth', 'somnacanth',
        'teostra', 'tetranadon', 'thunder_serpent_narwa', 'narwa_the_allmother',
        'tigrex', 'tobi-kadachi', 'crimson_glow_valstrax', 'volvidon', 'wind_serpent_ibushi',
        'zinogre', 'apex_zinogre', 
    ],
    sunbreak: [
        'magma_almudron', 'astalos', 'seething_bazelgeuse', 'blood_orange_bishaten',
        'risen_chameleos', 'daimyo_hermitaur', 'espinas', 'flaming_espinas',
        'gaismagorm', 'garangolm', 'gore_magala', 'chaotic_gore_magala', 'risen_kushala_daora',
        'lunagaron', 'scorned_magnamalo', 'malzeno', 'primordial_malzeno', 'violet_mizutsune',
        'lucent_nargacuga', 'furious_rajang', 'pyre_rakna-kadaki', 'silver_rathalos', 'gold_rathian',
        'seregios', 'shagaru_magala', 'risen_shagaru_magala', 'shogun_ceanataur', 'aurora_somnacanth',
        'risen_teostra', 'risen_crimson_glow_valstrax', 'velkhana', 
    ],
};
