'use strict';

var items_all = [
    {id: 'abyssal_lagiacrus', name: 'Abyssal Lagiacrus',
        image: 'Abyssal_Lagiacrus.png'},
    {id: 'acidic_glavenus', name: 'Acidic Glavenus',
        image: 'Acidic_Glavenus.png'},
    {id: 'agnaktor', name: 'Agnaktor',
        image: 'Agnaktor.png'},
    {id: 'ahtal-ka', name: 'Ahtal-Ka',
        image: 'Ahtal-Ka.png'},
    {id: 'ahtal-neset', name: 'Ahtal-Neset',
        image: 'Ahtal-Neset.png'},
    {id: 'akantor', name: 'Akantor',
        image: 'Akantor.png'},
    {id: 'aknosom', name: 'Aknosom',
        image: 'Aknosom.png'},
    {id: 'alatreon', name: 'Alatreon',
        image: 'Alatreon.png'},
    {id: 'almudron', name: 'Almudron',
        image: 'Almudron.png'},
    {id: 'amatsu', name: 'Amatsu',
        image: 'Amatsu.png'},
    {id: 'anjanath', name: 'Anjanath',
        image: 'Anjanath.png'},
    {id: 'apex_arzuros', name: 'Apex Arzuros',
        image: 'Apex_Arzuros.png'},
    {id: 'apex_diablos', name: 'Apex Diablos',
        image: 'Apex_Diablos.png'},
    {id: 'apex_mizutsune', name: 'Apex Mizutsune',
        image: 'Apex_Mizutsune.png'},
    {id: 'apex_rathalos', name: 'Apex Rathalos',
        image: 'Apex_Rathalos.png'},
    {id: 'apex_rathian', name: 'Apex Rathian',
        image: 'Apex_Rathian.png'},
    {id: 'apex_zinogre', name: 'Apex Zinogre',
        image: 'Apex_Zinogre.png'},
    {id: 'arzuros', name: 'Arzuros',
        image: 'Arzuros.png'},
    {id: 'ashen_lao-shan_lung', name: 'Ashen Lao-Shan Lung',
        image: 'Ashen_Lao-Shan_Lung.png'},
    {id: 'ash_kecha_wacha', name: 'Ash Kecha Wacha',
        image: 'Ash_Kecha_Wacha.png'},
    {id: 'astalos', name: 'Astalos',
        image: 'Astalos.png'},
    {id: 'aurora_somnacanth', name: 'Aurora Somnacanth',
        image: 'Aurora_Somnacanth.png'},
    {id: 'azure_rathalos', name: 'Azure Rathalos',
        image: 'Azure_Rathalos.png'},
    {id: 'baleful_gigginox', name: 'Baleful Gigginox',
        image: 'Baleful_Gigginox.png'},
    {id: 'banbaro', name: 'Banbaro',
        image: 'Banbaro.png'},
    {id: 'barioth', name: 'Barioth',
        image: 'Barioth.png'},
    {id: 'barroth', name: 'Barroth',
        image: 'Barroth.png'},
    {id: 'basarios', name: 'Basarios',
        image: 'Basarios.png'},
    {id: 'bazelgeuse', name: 'Bazelgeuse',
        image: 'Bazelgeuse.png'},
    {id: 'beotodus', name: 'Beotodus',
        image: 'Beotodus.png'},
    {id: 'berserk_tetsucabra', name: 'Berserk Tetsucabra',
        image: 'Berserk_Tetsucabra.png'},
    {id: 'bishaten', name: 'Bishaten',
        image: 'Bishaten.png'},
    {id: 'blackveil_vaal_hazak', name: 'Blackveil Vaal Hazak',
        image: 'Blackveil_Vaal_Hazak.png'},
    {id: 'black_diablos', name: 'Black Diablos',
        image: 'Black_Diablos.png'},
    {id: 'black_gravios', name: 'Black Gravios',
        image: 'Black_Gravios.png'},
    {id: 'blangonga', name: 'Blangonga',
        image: 'Blangonga.png'},
    {id: 'bloodbath_diablos', name: 'Bloodbath Diablos',
        image: 'Bloodbath_Diablos.png'},
    {id: 'blood_orange_bishaten', name: 'Blood Orange Bishaten',
        image: 'Blood_Orange_Bishaten.png'},
    {id: 'blue_yian_kut-ku', name: 'Blue Yian Kut-Ku',
        image: 'Blue_Yian_Kut-Ku.png'},
    {id: 'boltreaver_astalos', name: 'Boltreaver Astalos',
        image: 'Boltreaver_Astalos.png'},
    {id: 'brachydios', name: 'Brachydios',
        image: 'Brachydios.png'},
    {id: 'brute_tigrex', name: 'Brute Tigrex',
        image: 'Brute_Tigrex.png'},
    {id: 'bulldrome', name: 'Bulldrome',
        image: 'Bulldrome.png'},
    {id: 'ceadeus', name: 'Ceadeus',
        image: 'Ceadeus.png'},
    {id: 'cephadrome', name: 'Cephadrome',
        image: 'Cephadrome.png'},
    {id: 'chameleos', name: 'Chameleos',
        image: 'Chameleos.png'},
    {id: 'chaotic_gore_magala', name: 'Chaotic Gore Magala',
        image: 'Chaotic_Gore_Magala.png'},
    {id: 'congalala', name: 'Congalala',
        image: 'Congalala.png'},
    {id: 'copper_blangonga', name: 'Copper Blangonga',
        image: 'Copper_Blangonga.png'},
    {id: 'coral_pukei-pukei', name: 'Coral Pukei-Pukei',
        image: 'Coral_Pukei-Pukei.png'},
    {id: 'crimson_fatalis', name: 'Crimson Fatalis',
        image: 'Crimson_Fatalis.png'},
    {id: 'crimson_glow_valstrax', name: 'Crimson Glow Valstrax',
        image: 'Crimson_Glow_Valstrax.png'},
    {id: 'crimson_qurupeco', name: 'Crimson Qurupeco',
        image: 'Crimson_Qurupeco.png'},
    {id: 'crystalbeard_uragaan', name: 'Crystalbeard Uragaan',
        image: 'Crystalbeard_Uragaan.png'},
    {id: 'dah-ren_mohran', name: 'Dah\'ren Mohran',
        image: 'Dah\'ren_Mohran.png'},
    {id: 'daimyo_hermitaur', name: 'Daimyo Hermitaur',
        image: 'Daimyo_Hermitaur.png'},
    {id: 'dalamadur', name: 'Dalamadur',
        image: 'Dalamadur.png'},
    {id: 'deadeye_yian_garuga', name: 'Deadeye Yian Garuga',
        image: 'Deadeye_Yian_Garuga.png'},
    {id: 'desert_seltas', name: 'Desert Seltas',
        image: 'Desert_Seltas.png'},
    {id: 'desert_seltas_queen', name: 'Desert Seltas Queen',
        image: 'Desert_Seltas_Queen.png'},
    {id: 'deviljho', name: 'Deviljho',
        image: 'Deviljho.png'},
    {id: 'diablos', name: 'Diablos',
        image: 'Diablos.png'},
    {id: 'dire_miralis', name: 'Dire Miralis',
        image: 'Dire_Miralis.png'},
    {id: 'dodogama', name: 'Dodogama',
        image: 'Dodogama.png'},
    {id: 'dreadking_rathalos', name: 'Dreadking Rathalos',
        image: 'Dreadking_Rathalos.png'},
    {id: 'dreadqueen_rathian', name: 'Dreadqueen Rathian',
        image: 'Dreadqueen_Rathian.png'},
    {id: 'drilltusk_tetsucabra', name: 'Drilltusk Tetsucabra',
        image: 'Drilltusk_Tetsucabra.png'},
    {id: 'duramboros', name: 'Duramboros',
        image: 'Duramboros.png'},
    {id: 'ebony_odogaron', name: 'Ebony Odogaron',
        image: 'Ebony_Odogaron.png'},
    {id: 'elderfrost_gammoth', name: 'Elderfrost Gammoth',
        image: 'Elderfrost_Gammoth.png'},
    {id: 'emerald_congalala', name: 'Emerald Congalala',
        image: 'Emerald_Congalala.png'},
    {id: 'espinas', name: 'Espinas',
        image: 'Espinas.png'},
    {id: 'fatalis', name: 'Fatalis',
        image: 'Fatalis.png'},
    {id: 'flaming_espinas', name: 'Flaming Espinas',
        image: 'Flaming_Espinas.png'},
    {id: 'frostfang_barioth', name: 'Frostfang Barioth',
        image: 'Frostfang_Barioth.png'},
    {id: 'fulgur_anjanath', name: 'Fulgur Anjanath',
        image: 'Fulgur_Anjanath.png'},
    {id: 'furious_rajang', name: 'Furious Rajang',
        image: 'Furious_Rajang.png'},
    {id: 'gaismagorm', name: 'Gaismagorm',
        image: 'Gaismagorm.png'},
    {id: 'gammoth', name: 'Gammoth',
        image: 'Gammoth.png'},
    {id: 'garangolm', name: 'Garangolm',
        image: 'Garangolm.png'},
    {id: 'gendrome', name: 'Gendrome',
        image: 'Gendrome.png'},
    {id: 'giadrome', name: 'Giadrome',
        image: 'Giadrome.png'},
    {id: 'gigginox', name: 'Gigginox',
        image: 'Gigginox.png'},
    {id: 'glacial_agnaktor', name: 'Glacial Agnaktor',
        image: 'Glacial_Agnaktor.png'},
    {id: 'glavenus', name: 'Glavenus',
        image: 'Glavenus.png'},
    {id: 'gobul', name: 'Gobul',
        image: 'Gobul.png'},
    {id: 'gogmazios', name: 'Gogmazios',
        image: 'Gogmazios.png'},
    {id: 'goldbeard_ceadeus', name: 'Goldbeard Ceadeus',
        image: 'Goldbeard_Ceadeus.png'},
    {id: 'gold_rathian', name: 'Gold Rathian',
        image: 'Gold_Rathian.png'},
    {id: 'gore_magala', name: 'Gore Magala',
        image: 'Gore_Magala.png'},
    {id: 'goss_harag', name: 'Goss Harag',
        image: 'Goss_Harag.png'},
    {id: 'gravios', name: 'Gravios',
        image: 'Gravios.png'},
    {id: 'great_baggi', name: 'Great Baggi',
        image: 'Great_Baggi.png'},
    {id: 'great_girros', name: 'Great Girros',
        image: 'Great_Girros.png'},
    {id: 'great_izuchi', name: 'Great Izuchi',
        image: 'Great_Izuchi.png'},
    {id: 'great_jaggi', name: 'Great Jaggi',
        image: 'Great_Jaggi.png'},
    {id: 'great_jagras', name: 'Great Jagras',
        image: 'Great_Jagras.png'},
    {id: 'great_maccao', name: 'Great Maccao',
        image: 'Great_Maccao.png'},
    {id: 'great_wroggi', name: 'Great Wroggi',
        image: 'Great_Wroggi.png'},
    {id: 'green_nargacuga', name: 'Green Nargacuga',
        image: 'Green_Nargacuga.png'},
    {id: 'green_plesioth', name: 'Green Plesioth',
        image: 'Green_Plesioth.png'},
    {id: 'grimclaw_tigrex', name: 'Grimclaw Tigrex',
        image: 'Grimclaw_Tigrex.png'},
    {id: 'gypceros', name: 'Gypceros',
        image: 'Gypceros.png'},
    {id: 'hallowed_jhen_mohran', name: 'Hallowed Jhen Mohran',
        image: 'Hallowed_Jhen_Mohran.png'},
    {id: 'hellblade_glavenus', name: 'Hellblade Glavenus',
        image: 'Hellblade_Glavenus.png'},
    {id: 'hypnocatrice', name: 'Hypnocatrice',
        image: 'Hypnocatrice.png'},
    {id: 'iodrome', name: 'Iodrome',
        image: 'Iodrome.png'},
    {id: 'ivory_lagiacrus', name: 'Ivory Lagiacrus',
        image: 'Ivory_Lagiacrus.png'},
    {id: 'jade_barroth', name: 'Jade Barroth',
        image: 'Jade_Barroth.png'},
    {id: 'jhen_mohran', name: 'Jhen Mohran',
        image: 'Jhen_Mohran.png'},
    {id: 'jyuratodus', name: 'Jyuratodus',
        image: 'Jyuratodus.png'},
    {id: 'kecha_wacha', name: 'Kecha Wacha',
        image: 'Kecha_Wacha.png'},
    {id: 'khezu', name: 'Khezu',
        image: 'Khezu.png'},
    {id: 'king_shakalaka', name: 'King Shakalaka',
        image: 'King_Shakalaka.png'},
    {id: 'kirin', name: 'Kirin',
        image: 'Kirin.png'},
    {id: 'kulu-ya-ku', name: 'Kulu-Ya-Ku',
        image: 'Kulu-Ya-Ku.png'},
    {id: 'kulve_taroth', name: 'Kulve Taroth',
        image: 'Kulve_Taroth.png'},
    {id: 'kushala_daora', name: 'Kushala Daora',
        image: 'Kushala_Daora.png'},
    {id: 'lagiacrus', name: 'Lagiacrus',
        image: 'Lagiacrus.png'},
    {id: 'lagombi', name: 'Lagombi',
        image: 'Lagombi.png'},
    {id: 'lao-shan_lung', name: 'Lao-Shan Lung',
        image: 'Lao-Shan_Lung.png'},
    {id: 'lavasioth', name: 'Lavasioth',
        image: 'Lavasioth.png'},
    {id: 'legiana', name: 'Legiana',
        image: 'Legiana.png'},
    {id: 'lucent_nargacuga', name: 'Lucent Nargacuga',
        image: 'Lucent_Nargacuga.png'},
    {id: 'lunagaron', name: 'Lunagaron',
        image: 'Lunagaron.png'},
    {id: 'lunastra', name: 'Lunastra',
        image: 'Lunastra.png'},
    {id: 'magma_almudron', name: 'Magma Almudron',
        image: 'Magma_Almudron.png'},
    {id: 'magnamalo', name: 'Magnamalo',
        image: 'Magnamalo.png'},
    {id: 'malfestio', name: 'Malfestio',
        image: 'Malfestio.png'},
    {id: 'malzeno', name: 'Malzeno',
        image: 'Malzeno.png'},
    {id: 'mizutsune', name: 'Mizutsune',
        image: 'Mizutsune.png'},
    {id: 'molten_tigrex', name: 'Molten Tigrex',
        image: 'Molten_Tigrex.png'},
    {id: 'monoblos', name: 'Monoblos',
        image: 'Monoblos.png'},
    {id: 'najarala', name: 'Najarala',
        image: 'Najarala.png'},
    {id: 'nakarkos', name: 'Nakarkos',
        image: 'Nakarkos.png'},
    {id: 'namielle', name: 'Namielle',
        image: 'Namielle.png'},
    {id: 'nargacuga', name: 'Nargacuga',
        image: 'Nargacuga.png'},
    {id: 'narwa_the_allmother', name: 'Narwa the Allmother',
        image: 'Narwa_the_Allmother.png'},
    {id: 'nergigante', name: 'Nergigante',
        image: 'Nergigante.png'},
    {id: 'nerscylla', name: 'Nerscylla',
        image: 'Nerscylla.png'},
    {id: 'nibelsnarf', name: 'Nibelsnarf',
        image: 'Nibelsnarf.png'},
    {id: 'nightcloak_malfestio', name: 'Nightcloak Malfestio',
        image: 'Nightcloak_Malfestio.png'},
    {id: 'nightshade_paolumu', name: 'Nightshade Paolumu',
        image: 'Nightshade_Paolumu.png'},
    {id: 'odogaron', name: 'Odogaron',
        image: 'Odogaron.png'},
    {id: 'old_fatalis', name: 'Old Fatalis',
        image: 'Old_Fatalis.png'},
    {id: 'oroshi_kirin', name: 'Oroshi Kirin',
        image: 'Oroshi_Kirin.png'},
    {id: 'paolumu', name: 'Paolumu',
        image: 'Paolumu.png'},
    {id: 'pink_rathian', name: 'Pink Rathian',
        image: 'Pink_Rathian.png'},
    {id: 'plesioth', name: 'Plesioth',
        image: 'Plesioth.png'},
    {id: 'plum_daimyo_hermitaur', name: 'Plum Daimyo Hermitaur',
        image: 'Plum_Daimyo_Hermitaur.png'},
    {id: 'primordial_malzeno', name: 'Primordial Malzeno',
        image: 'Primordial_Malzeno.png'},
    {id: 'pukei-pukei', name: 'Pukei-Pukei',
        image: 'Pukei-Pukei.png'},
    {id: 'purple_gypceros', name: 'Purple Gypceros',
        image: 'Purple_Gypceros.png'},
    {id: 'purple_ludroth', name: 'Purple Ludroth',
        image: 'Purple_Ludroth.png'},
    {id: 'pyre_rakna-kadaki', name: 'Pyre Rakna-Kadaki',
        image: 'Pyre_Rakna-Kadaki.png'},
    {id: 'qurupeco', name: 'Qurupeco',
        image: 'Qurupeco.png'},
    {id: 'radobaan', name: 'Radobaan',
        image: 'Radobaan.png'},
    {id: 'raging_brachydios', name: 'Raging Brachydios',
        image: 'Raging_Brachydios.png'},
    {id: 'rajang', name: 'Rajang',
        image: 'Rajang.png'},
    {id: 'rakna-kadaki', name: 'Rakna-Kadaki',
        image: 'Rakna-Kadaki.png'},
    {id: 'rathalos', name: 'Rathalos',
        image: 'Rathalos.png'},
    {id: 'rathian', name: 'Rathian',
        image: 'Rathian.png'},
    {id: 'redhelm_arzuros', name: 'Redhelm Arzuros',
        image: 'Redhelm_Arzuros.png'},
    {id: 'red_khezu', name: 'Red Khezu',
        image: 'Red_Khezu.png'},
    {id: 'risen_chameleos', name: 'Risen Chameleos',
        image: 'Risen_Chameleos.png'},
    {id: 'risen_crimson_glow_valstrax', name: 'Risen Crimson Glow Valstrax',
        image: 'Risen_Crimson_Glow_Valstrax.png'},
    {id: 'risen_kushala_daora', name: 'Risen Kushala Daora',
        image: 'Risen_Kushala_Daora.png'},
    {id: 'risen_shagaru_magala', name: 'Risen Shagaru Magala',
        image: 'Risen_Shagaru_Magala.png'},
    {id: 'risen_teostra', name: 'Risen Teostra',
        image: 'Risen_Teostra.png'},
    {id: 'royal_ludroth', name: 'Royal Ludroth',
        image: 'Royal_Ludroth.png'},
    {id: 'ruby_basarios', name: 'Ruby Basarios',
        image: 'Ruby_Basarios.png'},
    {id: 'ruiner_nergigante', name: 'Ruiner Nergigante',
        image: 'Ruiner_Nergigante.png'},
    {id: 'rusted_kushala_daora', name: 'Rusted Kushala Daora',
        image: 'Rusted_Kushala_Daora.png'},
    {id: 'rustrazor_ceanataur', name: 'Rustrazor Ceanataur',
        image: 'Rustrazor_Ceanataur.png'},
    {id: 'rust_duramboros', name: 'Rust Duramboros',
        image: 'Rust_Duramboros.png'},
    {id: 'safi-jiiva', name: 'Safi\'jiiva',
        image: 'Safi\'jiiva.png'},
    {id: 'sand_barioth', name: 'Sand Barioth',
        image: 'Sand_Barioth.png'},
    {id: 'savage_deviljho', name: 'Savage Deviljho',
        image: 'Savage_Deviljho.png'},
    {id: 'scarred_yian_garuga', name: 'Scarred Yian Garuga',
        image: 'Scarred_Yian_Garuga.png'},
    {id: 'scorned_magnamalo', name: 'Scorned Magnamalo',
        image: 'Scorned_Magnamalo.png'},
    {id: 'seething_bazelgeuse', name: 'Seething Bazelgeuse',
        image: 'Seething_Bazelgeuse.png'},
    {id: 'seltas', name: 'Seltas',
        image: 'Seltas.png'},
    {id: 'seltas_queen', name: 'Seltas Queen',
        image: 'Seltas_Queen.png'},
    {id: 'seregios', name: 'Seregios',
        image: 'Seregios.png'},
    {id: 'shagaru_magala', name: 'Shagaru Magala',
        image: 'Shagaru_Magala.png'},
    {id: 'shah_dalamadur', name: 'Shah Dalamadur',
        image: 'Shah_Dalamadur.png'},
    {id: 'shara_ishvalda', name: 'Shara Ishvalda',
        image: 'Shara_Ishvalda.png'},
    {id: 'shen_gaoren', name: 'Shen Gaoren',
        image: 'Shen_Gaoren.png'},
    {id: 'shogun_ceanataur', name: 'Shogun Ceanataur',
        image: 'Shogun_Ceanataur.png'},
    {id: 'shrieking_legiana', name: 'Shrieking Legiana',
        image: 'Shrieking_Legiana.png'},
    {id: 'shrouded_nerscylla', name: 'Shrouded Nerscylla',
        image: 'Shrouded_Nerscylla.png'},
    {id: 'silverwind_nargacuga', name: 'Silverwind Nargacuga',
        image: 'Silverwind_Nargacuga.png'},
    {id: 'silver_rathalos', name: 'Silver Rathalos',
        image: 'Silver_Rathalos.png'},
    {id: 'snowbaron_lagombi', name: 'Snowbaron Lagombi',
        image: 'Snowbaron_Lagombi.png'},
    {id: 'somnacanth', name: 'Somnacanth',
        image: 'Somnacanth.png'},
    {id: 'soulseer_mizutsune', name: 'Soulseer Mizutsune',
        image: 'Soulseer_Mizutsune.png'},
    {id: 'steel_uragaan', name: 'Steel Uragaan',
        image: 'Steel_Uragaan.png'},
    {id: 'stonefist_hermitaur', name: 'Stonefist Hermitaur',
        image: 'Stonefist_Hermitaur.png'},
    {id: 'stygian_zinogre', name: 'Stygian Zinogre',
        image: 'Stygian_Zinogre.png'},
    {id: 'teostra', name: 'Teostra',
        image: 'Teostra.png'},
    {id: 'terra_shogun_ceanataur', name: 'Terra Shogun Ceanataur',
        image: 'Terra_Shogun_Ceanataur.png'},
    {id: 'tetranadon', name: 'Tetranadon',
        image: 'Tetranadon.png'},
    {id: 'tetsucabra', name: 'Tetsucabra',
        image: 'Tetsucabra.png'},
    {id: 'thunderlord_zinogre', name: 'Thunderlord Zinogre',
        image: 'Thunderlord_Zinogre.png'},
    {id: 'thunder_serpent_narwa', name: 'Thunder Serpent Narwa',
        image: 'Thunder_Serpent_Narwa.png'},
    {id: 'tidal_najarala', name: 'Tidal Najarala',
        image: 'Tidal_Najarala.png'},
    {id: 'tigerstripe_zamtrios', name: 'Tigerstripe Zamtrios',
        image: 'Tigerstripe_Zamtrios.png'},
    {id: 'tigrex', name: 'Tigrex',
        image: 'Tigrex.png'},
    {id: 'tobi-kadachi', name: 'Tobi-Kadachi',
        image: 'Tobi-Kadachi.png'},
    {id: 'tzitzi-ya-ku', name: 'Tzitzi-Ya-Ku',
        image: 'Tzitzi-Ya-Ku.png'},
    {id: 'ukanlos', name: 'Ukanlos',
        image: 'Ukanlos.png'},
    {id: 'uragaan', name: 'Uragaan',
        image: 'Uragaan.png'},
    {id: 'vaal_hazak', name: 'Vaal Hazak',
        image: 'Vaal_Hazak.png'},
    {id: 'valstrax', name: 'Valstrax',
        image: 'Valstrax.png'},
    {id: 'velkhana', name: 'Velkhana',
        image: 'Velkhana.png'},
    {id: 'velocidrome', name: 'Velocidrome',
        image: 'Velocidrome.png'},
    {id: 'vespoid_queen', name: 'Vespoid Queen',
        image: 'Vespoid_Queen.png'},
    {id: 'violet_mizutsune', name: 'Violet Mizutsune',
        image: 'Violet_Mizutsune.png'},
    {id: 'viper_tobi-kadachi', name: 'Viper Tobi-Kadachi',
        image: 'Viper_Tobi-Kadachi.png'},
    {id: 'volvidon', name: 'Volvidon',
        image: 'Volvidon.png'},
    {id: 'white_monoblos', name: 'White Monoblos',
        image: 'White_Monoblos.png'},
    {id: 'wind_serpent_ibushi', name: 'Wind Serpent Ibushi',
        image: 'Wind_Serpent_Ibushi.png'},
    {id: 'xeno-jiiva', name: 'Xeno\'jiiva',
        image: 'Xeno\'jiiva.png'},
    {id: 'yama_tsukami', name: 'Yama Tsukami',
        image: 'Yama_Tsukami.png'},
    {id: 'yian_garuga', name: 'Yian Garuga',
        image: 'Yian_Garuga.png'},
    {id: 'yian_kut-ku', name: 'Yian Kut-Ku',
        image: 'Yian_Kut-Ku.png'},
    {id: 'zamtrios', name: 'Zamtrios',
        image: 'Zamtrios.png'},
    {id: 'zinogre', name: 'Zinogre',
        image: 'Zinogre.png'},
    {id: 'zorah_magdaros', name: 'Zorah Magdaros',
        image: 'Zorah_Magdaros.png'},
];

var monsters_in_game = {
    world: [
        'anjanath', 'barroth', 'bazelgeuse', 'behemoth', 'deviljho', 'diablos', 'black_diablos',
        'dodogama', 'great_girros', 'great_jagras', 'jyuratodus',
        'kirin', 'kulu-ya-ku', 'kulve_taroth', 'kushala_daora', 'lavasioth', 'legiana', 'lunastra',
        'odogaron', 'nergigante', 'paolumu', 'pukei-pukei', 'radobaan',
        'rathalos', 'azure_rathalos', 'rathian', 'pink_rathian',
        'teostra', 'tobi-kadachi', 'tzitzi-ya-ku', 'uragaan', 'vaal_hazak',
        'xeno-jiiva', 'zorah_magdaros', 
    ],
    iceborne: [
        'alatreon', 'fulgur_anjanath', 'banbaro', 'barioth', 'frostfang_barioth',
        'seething_bazelgeuse', 'beotodus', 'brachydios', 'raging_brachydios', 'savage_deviljho',
        'fatalis', 'glavenus', 'acidic_glavenus', 'shrieking_legiana', 'ebony_odogaron', 'namielle',
        'nargacuga', 'ruiner_nergigante', 'nightshade_paolumu', 'coral_pukei-pukei',
        'rajang', 'furious_rajang', 'silver_rathalos', 'gold_rathian', 'safi-jiiva',
        'shara_ishvalda', 'tigrex', 'brute_tigrex', 'viper_tobi-kadachi', 'blackveil_vaal_hazak',
        'velkhana', 'yian_garuga', 'scarred_yian_garuga', 'zinogre', 'stygian_zinogre', 
    ],
    rise: [
        'aknosom', 'almudron', 'anjanath', 'arzuros', 'apex_arzuros',
        'barioth', 'barroth', 'bazelgeuse', 'basarios', 'bishaten', 'chameleos',
        'diablos', 'apex_diablos', 'goss_harag', 'great_baggi', 'great_izuchi', 'great_wroggi',
        'jyuratodus', 'khezu', 'kulu-ya-ku', 'kushala_daora', 'lagombi', 'magnamalo',
        'mizutsune', 'apex_mizutsune', 'nargacuga', 'pukei-pukei', 'rajang', 'rakna-kadaki',
        'rathalos', 'apex_rathalos', 'rathian', 'apex_rathian', 'royal_ludroth', 'somnacanth',
        'teostra', 'tetranadon', 'thunder_serpent_narwa', 'narwa_the_allmother',
        'tigrex', 'tobi-kadachi', 'crimson_glow_valstrax', 'volvidon', 'wind_serpent_ibushi',
        'zinogre', 'apex_zinogre', 
    ],
    sunbreak: [
        'magma_almudron', 'astalos', 'seething_bazelgeuse', 'blood_orange_bishaten',
        'risen_chameleos', 'daimyo_hermitaur', 'espinas', 'flaming_espinas',
        'gaismagorm', 'garangolm', 'gore_magala', 'chaotic_gore_magala', 'risen_kushala_daora',
        'lunagaron', 'scorned_magnamalo', 'malzeno', 'primordial_malzeno', 'violet_mizutsune',
        'lucent_nargacuga', 'furious_rajang', 'pyre_rakna-kadaki', 'silver_rathalos', 'gold_rathian',
        'seregios', 'shagaru_magala', 'risen_shagaru_magala', 'shogun_ceanataur', 'aurora_somnacanth',
        'risen_teostra', 'risen_crimson_glow_valstrax', 'velkhana', 
    ],
};
